#Generated by ActsAsFile
class <%= name %> < ActiveRecord::Base

  acts_as_file#This must come before any other methods defined by the plugin
  
  #Where to save images
  self.save_path = File.join(RAILS_ROOT, 'public', 'uploads')
  #Where the browser can find them
  self.read_path = 'uploads'

end